name: mp_alias_scanner
description: MercadoPago Alias Scanner - Real-time OCR for P2P transfers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  image: ^4.2.0
  path_provider: ^2.1.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

fonts:
  - family: Nunito
    fonts:
      - asset: fonts/Nunito-Black.ttf
        weight: 900
